# 1. Import libaries

In [3]:
import pandas as pd
import numpy as np

# 2. Load raw data

In [2]:
raw_data = pd.read_parquet("data/landing/foodpanda_analysis_dataset_2025.parquet", engine= "pyarrow")
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6000 non-null   str
 1   gender           6000 non-null   str
 2   age              6000 non-null   str
 3   city             6000 non-null   str
 4   signup_date      6000 non-null   str
 5   order_id         6000 non-null   str
 6   order_date       6000 non-null   str
 7   restaurant_name  6000 non-null   str
 8   dish_name        6000 non-null   str
 9   category         6000 non-null   str
 10  quantity         6000 non-null   int64
 11  price            6000 non-null   float64
 12  payment_method   6000 non-null   str
 13  order_frequency  6000 non-null   int64
 14  last_order_date  6000 non-null   str
 15  loyalty_points   6000 non-null   int64
 16  churned          6000 non-null   str
 17  rating           4032 non-null   float64
 18  rating_date      6000 non-null   str
 19  delivery_status  6000 non-null   str
dtypes: float64(2), int64(3), str(15)
memory usage: 1.5 MB

In [ ]:
# Preview data values
for col in raw_data.columns:
    print(f"\nColumn: {col}")
    print(f"Number of unique values: {raw_data[col].nunique(dropna=False)}")
    print(raw_data[col].value_counts(dropna=False))

Column: customer_id
Number of unique values: 6000
customer_id
C5663    1
C2831    1
C2851    1
C1694    1
C4339    1
        ..
C6849    1
C3787    1
C2841    1
C1624    1
C2068    1
Name: count, Length: 6000, dtype: int64

Column: gender
Number of unique values: 3
gender
Female    2018
Male      2017
Other     1965
Name: count, dtype: int64

Column: age
Number of unique values: 3
age
Teenager    2062
Adult       1984
Senior      1954
Name: count, dtype: int64

Column: city
Number of unique values: 5
city
Multan       1256
Lahore       1217
Peshawar     1195
Islamabad    1187
Karachi      1145
Name: count, dtype: int64

Column: signup_date
Number of unique values: 730
signup_date
10/18/2023    18
12/30/2024    16
1/26/2025     16
5/25/2025     16
7/18/2025     16
              ..
4/1/2025       2
11/23/2023     2
1/4/2025       2
12/14/2023     2
9/22/2023      2
Name: count, Length: 730, dtype: int64

Column: order_id
Number of unique values: 6000
order_id
O9663     1
O6831     1
O6851     1
O5694     1
O8339     1
         ..
O10849    1
O7787     1
O6841     1
O5624     1
O6068     1
Name: count, Length: 6000, dtype: int64

Column: order_date
Number of unique values: 730
order_date
9/8/2024      20
10/16/2023    17
9/12/2024     17
10/23/2023    16
12/3/2023     16
              ..
3/10/2024      2
5/11/2024      2
2/12/2025      2
5/12/2025      2
11/21/2023     1
Name: count, Length: 730, dtype: int64

Column: restaurant_name
Number of unique values: 5
restaurant_name
Subway         1260
KFC            1224
Pizza Hut      1224
Burger King    1151
McDonald's     1141
Name: count, dtype: int64

Column: dish_name
Number of unique values: 5
dish_name
Pasta       1262
Sandwich    1243
Pizza       1200
Fries       1152
Burger      1143
Name: count, dtype: int64

Column: category
Number of unique values: 5
category
Italian        1236
Fast Food      1222
Continental    1211
Chinese        1198
Dessert        1133
Name: count, dtype: int64

Column: quantity
Number of unique values: 5
quantity
3    1240
5    1208
1    1208
2    1197
4    1147
Name: count, dtype: int64

Column: price
Number of unique values: 5872
price
235.82     3
596.96     2
1044.89    2
275.53     2
1052.03    2
          ..
875.71     1
1118.26    1
1005.83    1
1226.10    1
1131.27    1
Name: count, Length: 5872, dtype: int64

Column: payment_method
Number of unique values: 3
payment_method
Cash      2039
Card      2002
Wallet    1959
Name: count, dtype: int64

Column: order_frequency
Number of unique values: 50
order_frequency
37    145
11    140
25    138
16    137
22    135
49    134
17    134
26    133
15    132
6     132
48    131
19    131
32    129
30    128
50    128
24    126
12    126
8     126
14    124
13    124
45    120
27    119
1     119
23    119
20    119
40    118
10    117
5     117
42    116
46    116
31    115
29    115
7     115
34    115
28    115
47    114
2     113
4     113
36    112
9     112
21    111
18    111
38    108
41    108
3     106
44    104
39    103
33    101
43     99
35     97
Name: count, dtype: int64

Column: last_order_date
Number of unique values: 366
last_order_date
2/6/2025      28
8/13/2025     28
5/16/2025     27
5/1/2025      25
4/8/2025      25
              ..
12/15/2024     8
5/22/2025      8
5/7/2025       7
2/17/2025      7
3/21/2025      6
Name: count, Length: 366, dtype: int64

Column: loyalty_points
Number of unique values: 501
loyalty_points
383    25
412    23
8      22
214    22
107    21
       ..
362     4
304     4
126     4
287     4
399     4
Name: count, Length: 501, dtype: int64

Column: churned
Number of unique values: 2
churned
Active      3016
Inactive    2984
Name: count, dtype: int64

Column: rating
Number of unique values: 6
rating
NaN    1968
3.0     829
4.0     811
5.0     810
1.0     800
2.0     782
Name: count, dtype: int64

Column: rating_date
Number of unique values: 366
rating_date
4/19/2025     27
6/14/2025     27
12/14/2024    27
10/4/2024     27
7/23/2025     27
              ..
2/7/2025       8
1/20/2025      8
5/1/2025       8
4/7/2025       7
8/27/2024      7
Name: count, Length: 366, dtype: int64

Column: delivery_status
Number of unique values: 3
delivery_status
Delivered    2060
Delayed      1972
Cancelled    1968
Name: count, dtype: int64

# 3. Data cleaning

In [54]:
# Clone df
df = raw_data.copy()

In [55]:
# Convert date cols
date_cols = ["signup_date", "order_date", "last_order_date", "rating_date"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce", format="%m/%d/%Y")

# Convert churned to binary
df["is_churned"] = df["churned"].map({"Inactive": 1, "Active": 0})

# Drop old cols
df.drop(columns=["churned"], inplace=True)

# Rename age cols
df.rename(columns={'age': 'age_group'}, inplace=True)

In [56]:
# Preview data values
for col in df.columns:
    print(f"\nColumn: {col}")
    print(f"Number of unique values: {df[col].nunique(dropna=False)}")
    print(df[col].value_counts(dropna=False))

Column: customer_id
Number of unique values: 6000
customer_id
C5663    1
C2831    1
C2851    1
C1694    1
C4339    1
        ..
C6849    1
C3787    1
C2841    1
C1624    1
C2068    1
Name: count, Length: 6000, dtype: int64

Column: gender
Number of unique values: 3
gender
Female    2018
Male      2017
Other     1965
Name: count, dtype: int64

Column: age_group
Number of unique values: 3
age_group
Teenager    2062
Adult       1984
Senior      1954
Name: count, dtype: int64

Column: city
Number of unique values: 5
city
Multan       1256
Lahore       1217
Peshawar     1195
Islamabad    1187
Karachi      1145
Name: count, dtype: int64

Column: signup_date
Number of unique values: 730
signup_date
2023-10-18    18
2024-12-30    16
2025-01-26    16
2025-05-25    16
2025-07-18    16
              ..
2025-04-01     2
2023-11-23     2
2025-01-04     2
2023-12-14     2
2023-09-22     2
Name: count, Length: 730, dtype: int64

Column: order_id
Number of unique values: 6000
order_id
O9663     1
O6831     1
O6851     1
O5694     1
O8339     1
         ..
O10849    1
O7787     1
O6841     1
O5624     1
O6068     1
Name: count, Length: 6000, dtype: int64

Column: order_date
Number of unique values: 730
order_date
2024-09-08    20
2023-10-16    17
2024-09-12    17
2023-10-23    16
2023-12-03    16
              ..
2024-03-10     2
2024-05-11     2
2025-02-12     2
2025-05-12     2
2023-11-21     1
Name: count, Length: 730, dtype: int64

Column: restaurant_name
Number of unique values: 5
restaurant_name
Subway         1260
KFC            1224
Pizza Hut      1224
Burger King    1151
McDonald's     1141
Name: count, dtype: int64

Column: dish_name
Number of unique values: 5
dish_name
Pasta       1262
Sandwich    1243
Pizza       1200
Fries       1152
Burger      1143
Name: count, dtype: int64

Column: category
Number of unique values: 5
category
Italian        1236
Fast Food      1222
Continental    1211
Chinese        1198
Dessert        1133
Name: count, dtype: int64

Column: quantity
Number of unique values: 5
quantity
3    1240
5    1208
1    1208
2    1197
4    1147
Name: count, dtype: int64

Column: price
Number of unique values: 5872
price
235.82     3
596.96     2
1044.89    2
275.53     2
1052.03    2
          ..
875.71     1
1118.26    1
1005.83    1
1226.10    1
1131.27    1
Name: count, Length: 5872, dtype: int64

Column: payment_method
Number of unique values: 3
payment_method
Cash      2039
Card      2002
Wallet    1959
Name: count, dtype: int64

Column: order_frequency
Number of unique values: 50
order_frequency
37    145
11    140
25    138
16    137
22    135
49    134
17    134
26    133
15    132
6     132
48    131
19    131
32    129
30    128
50    128
24    126
12    126
8     126
14    124
13    124
45    120
27    119
1     119
23    119
20    119
40    118
10    117
5     117
42    116
46    116
31    115
29    115
7     115
34    115
28    115
47    114
2     113
4     113
36    112
9     112
21    111
18    111
38    108
41    108
3     106
44    104
39    103
33    101
43     99
35     97
Name: count, dtype: int64

Column: last_order_date
Number of unique values: 366
last_order_date
2025-02-06    28
2025-08-13    28
2025-05-16    27
2025-05-01    25
2025-04-08    25
              ..
2024-12-15     8
2025-05-22     8
2025-05-07     7
2025-02-17     7
2025-03-21     6
Name: count, Length: 366, dtype: int64

Column: loyalty_points
Number of unique values: 501
loyalty_points
383    25
412    23
8      22
214    22
107    21
       ..
362     4
304     4
126     4
287     4
399     4
Name: count, Length: 501, dtype: int64

Column: rating
Number of unique values: 6
rating
NaN    1968
3.0     829
4.0     811
5.0     810
1.0     800
2.0     782
Name: count, dtype: int64

Column: rating_date
Number of unique values: 366
rating_date
2025-04-19    27
2025-06-14    27
2024-12-14    27
2024-10-04    27
2025-07-23    27
              ..
2025-02-07     8
2025-01-20     8
2025-05-01     8
2025-04-07     7
2024-08-27     7
Name: count, Length: 366, dtype: int64

Column: delivery_status
Number of unique values: 3
delivery_status
Delivered    2060
Delayed      1972
Cancelled    1968
Name: count, dtype: int64

Column: is_churned
Number of unique values: 2
is_churned
0    3016
1    2984
Name: count, dtype: int64

In [57]:
# Check dup record
df.duplicated().sum()

np.int64(0)

> No duplocated records

In [58]:
# Check missing col
print(df['rating'].unique())
df["rating"].describe([.01, .02, .05, .1, .2, .8, .9, .95, .97, .99])

[nan  2.  3.  4.  5.  1.]

count    4032.000000
mean        3.012153
std         1.411615
min         1.000000
1%          1.000000
2%          1.000000
5%          1.000000
10%         1.000000
20%         2.000000
80%         5.000000
90%         5.000000
95%         5.000000
97%         5.000000
99%         5.000000
max         5.000000
Name: rating, dtype: float64

In [64]:
# Fill missing rating with median
df['rating'] = df['rating'].fillna(3)

# Convert rating to int
df['rating'] = df['rating'].astype(int)

In [60]:
# Check invalid transaction
df[(df["quantity"] == 0) | (df["price"] == 0)]

Empty DataFrame
Columns: [customer_id, gender, age_group, city, signup_date, order_id, order_date, restaurant_name, dish_name, category, quantity, price, payment_method, order_frequency, last_order_date, loyalty_points, rating, rating_date, delivery_status, is_churned]
Index: []

> No invalid transation

In [61]:
df["value"] = df["quantity"] * df["price"]

In [66]:
df.head()

,customer_id,gender,age_group,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,...,price,payment_method,order_frequency,last_order_date,loyalty_points,rating,rating_date,delivery_status,is_churned,value
0,C5663,Male,Adult,Peshawar,2024-01-14,O9663,2023-08-23,McDonald's,Burger,Italian,...,1478.27,Cash,38,2025-07-19,238,3,2024-10-14,Cancelled,0,7391.35
1,C2831,Male,Adult,Multan,2024-07-07,O6831,2023-08-23,KFC,Burger,Italian,...,956.04,Wallet,24,2024-11-25,81,2,2025-08-21,Delayed,0,2868.12
2,C2851,Other,Senior,Multan,2025-06-20,O6851,2023-08-23,Pizza Hut,Fries,Italian,...,882.51,Cash,42,2025-05-10,82,3,2024-09-19,Delayed,1,1765.02
3,C1694,Female,Senior,Peshawar,2023-09-05,O5694,2023-08-23,Subway,Pizza,Dessert,...,231.30,Card,27,2025-07-24,45,2,2025-06-29,Delayed,1,925.20
4,C4339,Other,Senior,Lahore,2023-12-29,O8339,2023-08-24,KFC,Sandwich,Dessert,...,1156.69,Cash,35,2024-12-21,418,3,2025-03-06,Cancelled,1,1156.69

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6000 non-null   str
 1   gender           6000 non-null   str
 2   age_group        6000 non-null   str
 3   city             6000 non-null   str
 4   signup_date      6000 non-null   datetime64[us]
 5   order_id         6000 non-null   str
 6   order_date       6000 non-null   datetime64[us]
 7   restaurant_name  6000 non-null   str
 8   dish_name        6000 non-null   str
 9   category         6000 non-null   str
 10  quantity         6000 non-null   int64
 11  price            6000 non-null   float64
 12  payment_method   6000 non-null   str
 13  order_frequency  6000 non-null   int64
 14  last_order_date  6000 non-null   datetime64[us]
 15  loyalty_points   6000 non-null   int64
 16  rating           6000 non-null   int64
 17  rating_date      6000 non-null   datetime64[us]
 18  delivery_status  6000 non-null   str
 19  is_churned       6000 non-null   int64
 20  value            6000 non-null   float64
dtypes: datetime64[us](4), float64(2), int64(5), str(10)
memory usage: 1.3 MB

In [67]:
df.to_parquet(
    "data/staging/raw_data_cleaned.parquet",
    index=False,
    engine="pyarrow",
    compression="snappy"
)